version: '3.8'
services:
  arangodb:
    container_name: arangodb
    image: arangodb:3.9.1
    ports:
      - "8529:8529"
    command: ["arangod", "--cache.size", "1048576", "--rocksdb.block-cache-size", "1048576", "--rocksdb.enforce-block-cache-size-limit"]
    volumes:
      - arangodbdata:/var/lib/arangodb3
    environment:
      - ARANGO_NO_AUTH=1
    network_mode: bridge
volumes:
  arangodbdata: